package io.github.silicontaiga.money

/**
 * The data one shipped currency is defined by, before it becomes a [Currency].
 *
 * Kept separate from [Currency] itself so the shipped table is plain data: currency objects are
 * built from these once, by the registry, which is what keeps one code to one object.
 */
internal class CurrencyDefinition(
    val code: String,
    val scale: Int,
    val symbol: String,
)

/**
 * The currency definitions this library ships.
 *
 * ISO 4217 scales are the minor-unit exponents the standard assigns. The codes ISO marks as having
 * no minor unit — the precious metals, the bond market units, the IMF's `XDR`, the testing code
 * `XTS` and the "no currency" code `XXX` — are shipped at scale `0`.
 *
 * Symbols are labels, not formatting: many currencies have no distinctive one and fall back to
 * their code, and those that do have one frequently share it.
 */
internal object ShippedCurrencies {
    val iso: List<CurrencyDefinition> =
        listOf(
            CurrencyDefinition(code = "ADP", scale = 0, symbol = "ADP"),
            CurrencyDefinition(code = "AED", scale = 2, symbol = "د.إ."),
            CurrencyDefinition(code = "AFA", scale = 2, symbol = "AFA"),
            CurrencyDefinition(code = "AFN", scale = 2, symbol = "؋"),
            CurrencyDefinition(code = "ALL", scale = 2, symbol = "Lekë"),
            CurrencyDefinition(code = "AMD", scale = 2, symbol = "֏"),
            CurrencyDefinition(code = "ANG", scale = 2, symbol = "ANG"),
            CurrencyDefinition(code = "AOA", scale = 2, symbol = "Kz"),
            CurrencyDefinition(code = "ARS", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "ATS", scale = 2, symbol = "ATS"),
            CurrencyDefinition(code = "AUD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "AWG", scale = 2, symbol = "Afl."),
            CurrencyDefinition(code = "AYM", scale = 2, symbol = "AYM"),
            CurrencyDefinition(code = "AZM", scale = 2, symbol = "AZM"),
            CurrencyDefinition(code = "AZN", scale = 2, symbol = "₼"),
            CurrencyDefinition(code = "BAM", scale = 2, symbol = "KM"),
            CurrencyDefinition(code = "BBD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "BDT", scale = 2, symbol = "৳"),
            CurrencyDefinition(code = "BEF", scale = 0, symbol = "BEF"),
            CurrencyDefinition(code = "BGL", scale = 2, symbol = "BGL"),
            CurrencyDefinition(code = "BGN", scale = 2, symbol = "BGN"),
            CurrencyDefinition(code = "BHD", scale = 3, symbol = "د.ب."),
            CurrencyDefinition(code = "BIF", scale = 0, symbol = "FBu"),
            CurrencyDefinition(code = "BMD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "BND", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "BOB", scale = 2, symbol = "Bs"),
            CurrencyDefinition(code = "BOV", scale = 2, symbol = "BOV"),
            CurrencyDefinition(code = "BRL", scale = 2, symbol = "R$"),
            CurrencyDefinition(code = "BSD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "BTN", scale = 2, symbol = "Nu."),
            CurrencyDefinition(code = "BWP", scale = 2, symbol = "P"),
            CurrencyDefinition(code = "BYB", scale = 0, symbol = "BYB"),
            CurrencyDefinition(code = "BYN", scale = 2, symbol = "Br"),
            CurrencyDefinition(code = "BYR", scale = 0, symbol = "BYR"),
            CurrencyDefinition(code = "BZD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "CAD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "CDF", scale = 2, symbol = "FC"),
            CurrencyDefinition(code = "CHE", scale = 2, symbol = "CHE"),
            CurrencyDefinition(code = "CHF", scale = 2, symbol = "CHF"),
            CurrencyDefinition(code = "CHW", scale = 2, symbol = "CHW"),
            CurrencyDefinition(code = "CLF", scale = 4, symbol = "CLF"),
            CurrencyDefinition(code = "CLP", scale = 0, symbol = "$"),
            CurrencyDefinition(code = "CNY", scale = 2, symbol = "¥"),
            CurrencyDefinition(code = "COP", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "COU", scale = 2, symbol = "COU"),
            CurrencyDefinition(code = "CRC", scale = 2, symbol = "₡"),
            CurrencyDefinition(code = "CSD", scale = 2, symbol = "CSD"),
            CurrencyDefinition(code = "CUC", scale = 2, symbol = "CUC"),
            CurrencyDefinition(code = "CUP", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "CVE", scale = 2, symbol = "​"),
            CurrencyDefinition(code = "CYP", scale = 2, symbol = "CYP"),
            CurrencyDefinition(code = "CZK", scale = 2, symbol = "Kč"),
            CurrencyDefinition(code = "DEM", scale = 2, symbol = "DEM"),
            CurrencyDefinition(code = "DJF", scale = 0, symbol = "Fdj"),
            CurrencyDefinition(code = "DKK", scale = 2, symbol = "kr"),
            CurrencyDefinition(code = "DOP", scale = 2, symbol = "RD$"),
            CurrencyDefinition(code = "DZD", scale = 2, symbol = "DA"),
            CurrencyDefinition(code = "EEK", scale = 2, symbol = "EEK"),
            CurrencyDefinition(code = "EGP", scale = 2, symbol = "ج.م."),
            CurrencyDefinition(code = "ERN", scale = 2, symbol = "Nfk"),
            CurrencyDefinition(code = "ESP", scale = 0, symbol = "ESP"),
            CurrencyDefinition(code = "ETB", scale = 2, symbol = "Br"),
            CurrencyDefinition(code = "EUR", scale = 2, symbol = "€"),
            CurrencyDefinition(code = "FIM", scale = 2, symbol = "FIM"),
            CurrencyDefinition(code = "FJD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "FKP", scale = 2, symbol = "£"),
            CurrencyDefinition(code = "FRF", scale = 2, symbol = "FRF"),
            CurrencyDefinition(code = "GBP", scale = 2, symbol = "£"),
            CurrencyDefinition(code = "GEL", scale = 2, symbol = "₾"),
            CurrencyDefinition(code = "GHC", scale = 2, symbol = "GHC"),
            CurrencyDefinition(code = "GHS", scale = 2, symbol = "GH₵"),
            CurrencyDefinition(code = "GIP", scale = 2, symbol = "£"),
            CurrencyDefinition(code = "GMD", scale = 2, symbol = "D"),
            CurrencyDefinition(code = "GNF", scale = 0, symbol = "߿"),
            CurrencyDefinition(code = "GRD", scale = 0, symbol = "GRD"),
            CurrencyDefinition(code = "GTQ", scale = 2, symbol = "Q"),
            CurrencyDefinition(code = "GWP", scale = 2, symbol = "GWP"),
            CurrencyDefinition(code = "GYD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "HKD", scale = 2, symbol = "HK$"),
            CurrencyDefinition(code = "HNL", scale = 2, symbol = "L"),
            CurrencyDefinition(code = "HRK", scale = 2, symbol = "HRK"),
            CurrencyDefinition(code = "HTG", scale = 2, symbol = "G"),
            CurrencyDefinition(code = "HUF", scale = 2, symbol = "Ft"),
            CurrencyDefinition(code = "IDR", scale = 2, symbol = "Rp"),
            CurrencyDefinition(code = "IEP", scale = 2, symbol = "IEP"),
            CurrencyDefinition(code = "ILS", scale = 2, symbol = "₪"),
            CurrencyDefinition(code = "INR", scale = 2, symbol = "₹"),
            CurrencyDefinition(code = "IQD", scale = 3, symbol = "د.ع."),
            CurrencyDefinition(code = "IRR", scale = 2, symbol = "ریال"),
            CurrencyDefinition(code = "ISK", scale = 0, symbol = "kr."),
            CurrencyDefinition(code = "ITL", scale = 0, symbol = "ITL"),
            CurrencyDefinition(code = "JMD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "JOD", scale = 3, symbol = "د.أ."),
            CurrencyDefinition(code = "JPY", scale = 0, symbol = "¥"),
            CurrencyDefinition(code = "KES", scale = 2, symbol = "Ksh"),
            CurrencyDefinition(code = "KGS", scale = 2, symbol = "сом"),
            CurrencyDefinition(code = "KHR", scale = 2, symbol = "៛"),
            CurrencyDefinition(code = "KMF", scale = 0, symbol = "CF"),
            CurrencyDefinition(code = "KPW", scale = 2, symbol = "KPW"),
            CurrencyDefinition(code = "KRW", scale = 0, symbol = "₩"),
            CurrencyDefinition(code = "KWD", scale = 3, symbol = "د.ك."),
            CurrencyDefinition(code = "KYD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "KZT", scale = 2, symbol = "₸"),
            CurrencyDefinition(code = "LAK", scale = 2, symbol = "₭"),
            CurrencyDefinition(code = "LBP", scale = 2, symbol = "ل.ل."),
            CurrencyDefinition(code = "LKR", scale = 2, symbol = "Rs."),
            CurrencyDefinition(code = "LRD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "LSL", scale = 2, symbol = "M"),
            CurrencyDefinition(code = "LTL", scale = 2, symbol = "LTL"),
            CurrencyDefinition(code = "LUF", scale = 0, symbol = "LUF"),
            CurrencyDefinition(code = "LVL", scale = 2, symbol = "LVL"),
            CurrencyDefinition(code = "LYD", scale = 3, symbol = "د.ل."),
            CurrencyDefinition(code = "MAD", scale = 2, symbol = "د.م."),
            CurrencyDefinition(code = "MDL", scale = 2, symbol = "L"),
            CurrencyDefinition(code = "MGA", scale = 2, symbol = "Ar"),
            CurrencyDefinition(code = "MGF", scale = 0, symbol = "MGF"),
            CurrencyDefinition(code = "MKD", scale = 2, symbol = "den"),
            CurrencyDefinition(code = "MMK", scale = 2, symbol = "K"),
            CurrencyDefinition(code = "MNT", scale = 2, symbol = "₮"),
            CurrencyDefinition(code = "MOP", scale = 2, symbol = "MOP$"),
            CurrencyDefinition(code = "MRO", scale = 2, symbol = "MRO"),
            CurrencyDefinition(code = "MRU", scale = 2, symbol = "UM"),
            CurrencyDefinition(code = "MTL", scale = 2, symbol = "MTL"),
            CurrencyDefinition(code = "MUR", scale = 2, symbol = "Rs"),
            CurrencyDefinition(code = "MVR", scale = 2, symbol = "Rf"),
            CurrencyDefinition(code = "MWK", scale = 2, symbol = "MK"),
            CurrencyDefinition(code = "MXN", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "MXV", scale = 2, symbol = "MXV"),
            CurrencyDefinition(code = "MYR", scale = 2, symbol = "RM"),
            CurrencyDefinition(code = "MZM", scale = 2, symbol = "MZM"),
            CurrencyDefinition(code = "MZN", scale = 2, symbol = "MTn"),
            CurrencyDefinition(code = "NAD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "NGN", scale = 2, symbol = "₦"),
            CurrencyDefinition(code = "NIO", scale = 2, symbol = "C$"),
            CurrencyDefinition(code = "NLG", scale = 2, symbol = "NLG"),
            CurrencyDefinition(code = "NOK", scale = 2, symbol = "kr"),
            CurrencyDefinition(code = "NPR", scale = 2, symbol = "नेरू"),
            CurrencyDefinition(code = "NZD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "OMR", scale = 3, symbol = "ر.ع."),
            CurrencyDefinition(code = "PAB", scale = 2, symbol = "B/."),
            CurrencyDefinition(code = "PEN", scale = 2, symbol = "S/"),
            CurrencyDefinition(code = "PGK", scale = 2, symbol = "K"),
            CurrencyDefinition(code = "PHP", scale = 2, symbol = "₱"),
            CurrencyDefinition(code = "PKR", scale = 2, symbol = "ر"),
            CurrencyDefinition(code = "PLN", scale = 2, symbol = "zł"),
            CurrencyDefinition(code = "PTE", scale = 0, symbol = "PTE"),
            CurrencyDefinition(code = "PYG", scale = 0, symbol = "Gs."),
            CurrencyDefinition(code = "QAR", scale = 2, symbol = "ر.ق."),
            CurrencyDefinition(code = "ROL", scale = 0, symbol = "ROL"),
            CurrencyDefinition(code = "RON", scale = 2, symbol = "RON"),
            CurrencyDefinition(code = "RSD", scale = 2, symbol = "RSD"),
            CurrencyDefinition(code = "RUB", scale = 2, symbol = "₽"),
            CurrencyDefinition(code = "RUR", scale = 2, symbol = "RUR"),
            CurrencyDefinition(code = "RWF", scale = 0, symbol = "RF"),
            CurrencyDefinition(code = "SAR", scale = 2, symbol = "ر.س."),
            CurrencyDefinition(code = "SBD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "SCR", scale = 2, symbol = "SR"),
            CurrencyDefinition(code = "SDD", scale = 2, symbol = "SDD"),
            CurrencyDefinition(code = "SDG", scale = 2, symbol = "ج.س."),
            CurrencyDefinition(code = "SEK", scale = 2, symbol = "kr"),
            CurrencyDefinition(code = "SGD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "SHP", scale = 2, symbol = "£"),
            CurrencyDefinition(code = "SIT", scale = 2, symbol = "SIT"),
            CurrencyDefinition(code = "SKK", scale = 2, symbol = "SKK"),
            CurrencyDefinition(code = "SLE", scale = 2, symbol = "Le"),
            CurrencyDefinition(code = "SLL", scale = 2, symbol = "SLL"),
            CurrencyDefinition(code = "SOS", scale = 2, symbol = "S"),
            CurrencyDefinition(code = "SRD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "SRG", scale = 2, symbol = "SRG"),
            CurrencyDefinition(code = "SSP", scale = 2, symbol = "£"),
            CurrencyDefinition(code = "STD", scale = 2, symbol = "STD"),
            CurrencyDefinition(code = "STN", scale = 2, symbol = "Db"),
            CurrencyDefinition(code = "SVC", scale = 2, symbol = "SVC"),
            CurrencyDefinition(code = "SYP", scale = 2, symbol = "LS"),
            CurrencyDefinition(code = "SZL", scale = 2, symbol = "E"),
            CurrencyDefinition(code = "THB", scale = 2, symbol = "฿"),
            CurrencyDefinition(code = "TJS", scale = 2, symbol = "сом."),
            CurrencyDefinition(code = "TMM", scale = 2, symbol = "TMM"),
            CurrencyDefinition(code = "TMT", scale = 2, symbol = "TMT"),
            CurrencyDefinition(code = "TND", scale = 3, symbol = "DT"),
            CurrencyDefinition(code = "TOP", scale = 2, symbol = "T$"),
            CurrencyDefinition(code = "TPE", scale = 0, symbol = "TPE"),
            CurrencyDefinition(code = "TRL", scale = 0, symbol = "TRL"),
            CurrencyDefinition(code = "TRY", scale = 2, symbol = "₺"),
            CurrencyDefinition(code = "TTD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "TWD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "TZS", scale = 2, symbol = "TSh"),
            CurrencyDefinition(code = "UAH", scale = 2, symbol = "₴"),
            CurrencyDefinition(code = "UGX", scale = 0, symbol = "USh"),
            CurrencyDefinition(code = "USD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "USN", scale = 2, symbol = "USN"),
            CurrencyDefinition(code = "USS", scale = 2, symbol = "USS"),
            CurrencyDefinition(code = "UYI", scale = 0, symbol = "UYI"),
            CurrencyDefinition(code = "UYU", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "UZS", scale = 2, symbol = "сўм"),
            CurrencyDefinition(code = "VEB", scale = 2, symbol = "VEB"),
            CurrencyDefinition(code = "VED", scale = 2, symbol = "VED"),
            CurrencyDefinition(code = "VEF", scale = 2, symbol = "VEF"),
            CurrencyDefinition(code = "VES", scale = 2, symbol = "Bs.S"),
            CurrencyDefinition(code = "VND", scale = 0, symbol = "₫"),
            CurrencyDefinition(code = "VUV", scale = 0, symbol = "VT"),
            CurrencyDefinition(code = "WST", scale = 2, symbol = "WS$"),
            CurrencyDefinition(code = "XAD", scale = 2, symbol = "XAD"),
            CurrencyDefinition(code = "XAF", scale = 0, symbol = "FCFA"),
            CurrencyDefinition(code = "XAG", scale = 0, symbol = "XAG"),
            CurrencyDefinition(code = "XAU", scale = 0, symbol = "XAU"),
            CurrencyDefinition(code = "XBA", scale = 0, symbol = "XBA"),
            CurrencyDefinition(code = "XBB", scale = 0, symbol = "XBB"),
            CurrencyDefinition(code = "XBC", scale = 0, symbol = "XBC"),
            CurrencyDefinition(code = "XBD", scale = 0, symbol = "XBD"),
            CurrencyDefinition(code = "XCD", scale = 2, symbol = "$"),
            CurrencyDefinition(code = "XCG", scale = 2, symbol = "Cg."),
            CurrencyDefinition(code = "XDR", scale = 0, symbol = "XDR"),
            CurrencyDefinition(code = "XFO", scale = 0, symbol = "XFO"),
            CurrencyDefinition(code = "XFU", scale = 0, symbol = "XFU"),
            CurrencyDefinition(code = "XOF", scale = 0, symbol = "F CFA"),
            CurrencyDefinition(code = "XPD", scale = 0, symbol = "XPD"),
            CurrencyDefinition(code = "XPF", scale = 0, symbol = "FCFP"),
            CurrencyDefinition(code = "XPT", scale = 0, symbol = "XPT"),
            CurrencyDefinition(code = "XSU", scale = 0, symbol = "XSU"),
            CurrencyDefinition(code = "XTS", scale = 0, symbol = "XTS"),
            CurrencyDefinition(code = "XUA", scale = 0, symbol = "XUA"),
            CurrencyDefinition(code = "XXX", scale = 0, symbol = "XXX"),
            CurrencyDefinition(code = "YER", scale = 2, symbol = "ر.ي."),
            CurrencyDefinition(code = "YUM", scale = 2, symbol = "YUM"),
            CurrencyDefinition(code = "ZAR", scale = 2, symbol = "R"),
            CurrencyDefinition(code = "ZMK", scale = 2, symbol = "ZMK"),
            CurrencyDefinition(code = "ZMW", scale = 2, symbol = "K"),
            CurrencyDefinition(code = "ZWD", scale = 2, symbol = "ZWD"),
            CurrencyDefinition(code = "ZWG", scale = 2, symbol = "ZWG"),
            CurrencyDefinition(code = "ZWL", scale = 2, symbol = "ZWL"),
            CurrencyDefinition(code = "ZWN", scale = 2, symbol = "ZWN"),
            CurrencyDefinition(code = "ZWR", scale = 2, symbol = "ZWR"),
        )

    val crypto: List<CurrencyDefinition> =
        listOf(
            CurrencyDefinition(code = "1INCH", scale = 18, symbol = "1INCH"),
            CurrencyDefinition(code = "ADA", scale = 6, symbol = "₳"),
            CurrencyDefinition(code = "ATOM", scale = 6, symbol = "ATOM"),
            CurrencyDefinition(code = "AVAX", scale = 18, symbol = "AVAX"),
            CurrencyDefinition(code = "BCH", scale = 8, symbol = "BCH"),
            CurrencyDefinition(code = "BNB", scale = 18, symbol = "BNB"),
            CurrencyDefinition(code = "BTC", scale = 8, symbol = "₿"),
            CurrencyDefinition(code = "DOGE", scale = 8, symbol = "Ð"),
            CurrencyDefinition(code = "DOT", scale = 10, symbol = "DOT"),
            CurrencyDefinition(code = "ETH", scale = 18, symbol = "Ξ"),
            CurrencyDefinition(code = "LINK", scale = 18, symbol = "LINK"),
            CurrencyDefinition(code = "LTC", scale = 8, symbol = "Ł"),
            CurrencyDefinition(code = "SHIB", scale = 18, symbol = "SHIB"),
            CurrencyDefinition(code = "SOL", scale = 9, symbol = "◎"),
            CurrencyDefinition(code = "TRX", scale = 6, symbol = "TRX"),
            CurrencyDefinition(code = "UNI", scale = 18, symbol = "UNI"),
            CurrencyDefinition(code = "USDC", scale = 6, symbol = "USDC"),
            CurrencyDefinition(code = "USDT", scale = 6, symbol = "₮"),
            CurrencyDefinition(code = "XMR", scale = 12, symbol = "ɱ"),
            CurrencyDefinition(code = "XRP", scale = 6, symbol = "XRP"),
        )

    val all: List<CurrencyDefinition> = iso + crypto
}

/**
 * The currency sets this library ships, as they are currently in force.
 *
 * Both are views rather than snapshots: a currency replaced through [Money.configure] appears here
 * in its replaced form. Currencies an application adds of its own belong to neither set.
 */
public object Currencies {
    /** Every ISO 4217 currency, including those since withdrawn. */
    public val iso: List<Currency>
        get() = ShippedCurrencies.iso.map { Currency.of(it.code) }

    /** Every cryptocurrency this library ships. */
    public val crypto: List<Currency>
        get() = ShippedCurrencies.crypto.map { Currency.of(it.code) }
}
